from tkinter import *
root= Tk()
root.title("Rock Paper Scissors Lizard Spock")
root.configure(background="blue")
user_indicator = Label(root, font=50, text="Player1", bg="blue", fg="white")
user_indicator.grid(row=0, column=3)
user_indicator = Label(root, font=50, text ="Computer", bg="blue", fg="white")
user_indicator.grid(row=0, column=9)
button = Button(root, text="Rock")
button.grid(row=3, column=4)
button = Button(root, text="Paper")
button.grid(row=3, column=5)
button = Button(root, text="Scissors")
button.grid(row=3, column=6)
button = Button(root, text="Lizard")
button.grid(row=3, column=7)
button = Button(root, text="Spock")
button.grid(row=3, column=8)
playerscor = Label(root, font=50, text=0, bg="blue", fg="white")
playerscor.grid(row=0, column=4)
computerscor = Label(root, font=50, text=0, bg="blue", fg="white")
computerscor.grid(row=0, column=8)
root.mainloop()
